SET SERVEROUTPUT ON;
DECLARE
CURSOR C IS
    SELECT BALANCE,ACCOUNT_NO,NAME FROM CUSTOMER;
C_RECORD C%ROWTYPE;
A CUSTOMER.BALANCE%TYPE;


BEGIN
    OPEN C;
    LOOP
        FETCH C INTO C_RECORD;
        EXIT WHEN C%NOTFOUND;   

        SELECT SUM(AMOUNT) INTO A FROM LOAN WHERE ACCOUNT_NO = C_RECORD.ACCOUNT_NO;
        IF A <= C_RECORD.ACCOUNT_NO
        THEN
            A :=A - C_RECORD.BALANCE;
            
            IF A >=50000
            THEN
            	DBMS_OUTPUT.PUT_LINE('YOU ARE ELIGIBLE TO GET CREDIT CARD MR. '||C_RECORD.NAME);
            ELSE
            	DBMS_OUTPUT.PUT_LINE('SORRY '||'MR. '||C_RECORD.NAME||' .YOUR BALANCE IS INSUFFICIENT');

            END IF;
        END IF;
        ELSE
            DBMS_OUTPUT.PUT_LINE('SORRY '||'MR. '||C_RECORD.NAME||' .YOUR BALANCE IS INSUFFICIENT');

    END LOOP;
    CLOSE C;
END;
/