SET SERVEROUTPUT ON;

DECLARE

F UTL_FILE.FILE_TYPE;
LINE VARCHAR(1000);
ACCOUNT_NO1 CUSTOMER.ACCOUNT_NO%TYPE;
NAME1       CUSTOMER.NAME%TYPE;
DOB1        CUSTOMER.DATE_OF_BIRTH%TYPE;
GENDER1     CUSTOMER.GENDER%TYPE;
BRANCH1     CUSTOMER.BRANCH_NAME%TYPE;
PHONE1      CUSTOMER.PHONE_NO%TYPE;
BALANCE1    CUSTOMER.BALANCE%TYPE;
ACCTYPE1    CUSTOMER.ACCOUNT_TYPE%TYPE;    

BEGIN
    F := UTL_FILE.FOPEN('CSE','Customer.csv','R');
    IF UTL_FILE.IS_OPEN(F) THEN 
    UTL_FILE.GET_LINE(F,LINE,1000);
    /*DBMS_OUTPUT.PUT_LINE(LINE);*/
    LOOP BEGIN
    UTL_FILE.GET_LINE(F,LINE,1000);
    IF LINE IS NULL THEN EXIT;
    END IF;
    /*DBMS_OUTPUT.PUT_LINE(LINE);*/
    ACCOUNT_NO1 := REGEXP_SUBSTR(LINE,'[^,]+',1,1);
    DOB1        := REGEXP_SUBSTR(LINE,'[^,]+',1,3);
    NAME1       := REGEXP_SUBSTR(LINE,'[^,]+',1,2);
    GENDER1     := REGEXP_SUBSTR(LINE,'[^,]+',1,4);
    BRANCH1     := REGEXP_SUBSTR(LINE,'[^,]+',1,5);
    PHONE1      := REGEXP_SUBSTR(LINE,'[^,]+',1,6);
    BALANCE1    := REGEXP_SUBSTR(LINE,'[^,]+',1,7);
    ACCTYPE1    := REGEXP_SUBSTR(LINE,'[^,]+',1,8);
    
    INSERT INTO CUSTOMER VALUES(ACCOUNT_NO1,NAME1,DOB1,GENDER1,BRANCH1,PHONE1,BALANCE1,ACCTYPE1);
    COMMIT;
    EXCEPTION WHEN NO_DATA_FOUND THEN EXIT;
    END;
    END LOOP;
    END IF;
    UTL_FILE.FCLOSE(F);
END;
/
