SET SERVEROUTPUT ON;

DECLARE

F UTL_FILE.FILE_TYPE;
LINE VARCHAR(1000);

NAME1       BRANCH.BRANCH_NAME%TYPE;
CITY1       BRANCH.CITY%TYPE;

    

BEGIN
    F := UTL_FILE.FOPEN('CSE','Branch.csv','R');
    IF UTL_FILE.IS_OPEN(F) THEN 
    UTL_FILE.GET_LINE(F,LINE,1000);
    /*DBMS_OUTPUT.PUT_LINE(LINE);*/
    LOOP BEGIN
    UTL_FILE.GET_LINE(F,LINE,1000);
    IF LINE IS NULL THEN EXIT;
    END IF;
    /*DBMS_OUTPUT.PUT_LINE(LINE);*/

    NAME1     := REGEXP_SUBSTR(LINE,'[^,]+',1,1);
    CITY1     := REGEXP_SUBSTR(LINE,'[^,]+',1,2);
 
    
    
    INSERT INTO BRANCH VALUES(NAME1,CITY1);
    COMMIT;
    EXCEPTION WHEN NO_DATA_FOUND THEN EXIT;
    END;
    END LOOP;
    END IF;
    UTL_FILE.FCLOSE(F);
END;
/
