SET SERVEROUTPUT ON;

DECLARE

F UTL_FILE.FILE_TYPE;
LINE VARCHAR(1000);
LOAN_NO1    LOAN.LOAN_NO%TYPE;
ACCOUNT_NO1 LOAN.ACCOUNT_NO%TYPE;
LOAN_TYPE1  LOAN.LOAN_TYPE%TYPE;
INTEREST1   LOAN.INTEREST%TYPE;
CLERK1      LOAN.ENTRY_CLERK_ID%TYPE;
ACCESS1     LOAN.ACCESS_DATE%TYPE;
AMOUNT1     LOAN.AMOUNT%TYPE;
    

BEGIN
    F := UTL_FILE.FOPEN('CSE','Loan.csv','R');
    IF UTL_FILE.IS_OPEN(F) THEN 
    UTL_FILE.GET_LINE(F,LINE,1000);
    /*DBMS_OUTPUT.PUT_LINE(LINE);*/
    LOOP BEGIN
    UTL_FILE.GET_LINE(F,LINE,1000);
    IF LINE IS NULL THEN EXIT;
    END IF;
    /*DBMS_OUTPUT.PUT_LINE(LINE);*/
    ACCOUNT_NO1 := REGEXP_SUBSTR(LINE,'[^,]+',1,2);
    LOAN_NO1    := REGEXP_SUBSTR(LINE,'[^,]+',1,1);
    LOAN_TYPE1  := REGEXP_SUBSTR(LINE,'[^,]+',1,3);
    INTEREST1   := REGEXP_SUBSTR(LINE,'[^,]+',1,4);
    CLERK1      := REGEXP_SUBSTR(LINE,'[^,]+',1,5);
    ACCESS1     := REGEXP_SUBSTR(LINE,'[^,]+',1,6);
    AMOUNT1     := REGEXP_SUBSTR(LINE,'[^,]+',1,7);
    
    
    INSERT INTO CUSTOMER VALUES(LOAN_NO,ACCOUNT_NO1,LOAN_TYPE1,INTEREST1,CLERK1,ACCESS1,AMOUNT1);
    COMMIT;
    EXCEPTION WHEN NO_DATA_FOUND THEN EXIT;
    END;
    END LOOP;
    END IF;
    UTL_FILE.FCLOSE(F);
END;
/
