SET SERVEROUTPUT ON;
DECLARE
TYPE NAMELIST IS VARRAY(15) OF VARCHAR(20);
MYARR NAMELIST := NAMELIST();
COUNTER INTEGER :=0;
CURSOR C(PASS BRANCH.BRANCH_NAME%TYPE) IS SELECT DISTINCT(NAME) FROM CUSTOMER 
			WHERE BRANCH_NAME IN(SELECT DISTINCT(BRANCH_NAME) FROM CUSTOMER WHERE ACCOUNT_NO IN(
				SELECT DISTINCT(ACCOUNT_NO) FROM CUSTOMER C NATURAL JOIN LOAN L WHERE BRANCH_NAME=PASS)); 
C_NAME CUSTOMER.NAME%TYPE;


PROCEDURE listLoanBranch(x IN BRANCH.BRANCH_NAME%TYPE) IS 
BEGIN
	
	OPEN C(x);
	LOOP
	FETCH C INTO C_NAME;
	EXIT WHEN C%NOTFOUND;
	COUNTER :=COUNTER+1;
	MYARR.EXTEND;
	MYARR(COUNTER) :=C_NAME;

	END LOOP;
	dbms_output.put_line('List of student: ');
	FOR i IN 1..MYARR.count LOOP
	        dbms_output.put_line(MYARR(i));
	    END LOOP;
	CLOSE C;
END;

BEGIN
	listLoanBranch('KUET');
    
END;
/
/

