SET SERVEROUTPUT ON;

DECLARE

F UTL_FILE.FILE_TYPE;
CURSOR C IS SELECT * FROM CUSTOMER WHERE BRANCH_NAME='KUET';

BEGIN
    F := UTL_FILE.FOPEN('CSE','KUET.csv','W');
    UTL_FILE.PUT(F,'ACCOUNT_NO'||','||'NAME'||','||'DATE_OF_BIRTH'||','||'GENDER'||','||'BRANCH_NAME'||','||'PHONE_NO'||','||'BALANCE'||','||'ACCOUNT_TYPE');
    UTL_FILE.NEW_LINE(F);
    FOR C_RECORD IN C
    LOOP
        UTL_FILE.PUT(F,C_RECORD.ACCOUNT_NO||','||C_RECORD.NAME||','||C_RECORD.DATE_OF_BIRTH||','||C_RECORD.GENDER||','||C_RECORD.BRANCH_NAME||','||C_RECORD.PHONE_NO||','||C_RECORD.BALANCE||','||C_RECORD.ACCOUNT_TYPE);
        UTL_FILE.NEW_LINE(F);
    END LOOP;
    UTL_FILE.FCLOSE(F);
    
END;
/
